services:
  backend:
    build: ./back-job-app
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./back-job-app:/app
      - /app/node_modules
  frontend:
    build: ./front-job-app
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - REACT_APP_API_URL=http://backend:5000/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./front-job-app:/app
      - /app/node_modules
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./front-job-app
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - backend
